[program:oneport-linux]
command=%(ENV_RESOURCES_PATH)s/oneport/oneport-linux %(ENV_RESOURCES_PATH)s/oneport/config.json
priority=53
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
